### ISSUE TITLE
Active watcher roadmap

### ISSUE THREAD

**Issue by pi0** [unjs/unbuild#281]
Related: #265, https://github.com/unjs/unbuild/issues/20

Support `unbuild --watch` to run rollup in watch mode.

Roadmap:

- [x] Rollup watcher for `mjs` and `cjs` entries (via #364 thanks to @joemckenney)
- [ ] Rollup dts watcher support
- [ ] Mkdist watcher support
- [ ] Untyped watcher support
- [ ] Copy watcher support

**Comment by jbaubree** [comment]
@pi0 can't wait to get this feature 👍

**Comment by joemckenney** [comment]
@pi0 would you be open to a non-rollup implementation?  If so, happy to contribute.  We wrapped unbuild when building our own CLI build tool and implemented an active watcher w/ nodemon.  You can see the implementation [here](https://github.com/dopt/odopt/blob/main/packages/%40dopt/pkg/build/src/cli.ts#L38-L47).  If interested, I'd be happy to implement a more generic/robust version of this in unbuild directly.

**Comment by AbhiPrasad** [comment]
Any appetite to this? Would you accept PRs for this change? Should we expose all of rollup watch config (delay, include, exclude)?

**Comment by pi0** [comment]
We can start by supporting rollup watcher only. I think passing all watcher options should also be okay with some preconfigured defaults. @AbhiPrasad feel free to make a draft PR (preferably with as small changes as possible to allow moving forward quickly 🙏🏼 )

**Comment by AbhiPrasad** [comment]
Sounds like a plan - will take a look this weekend. Another q - what should happen when someone tried to do watch mode + stub mode at the same time?

**Comment by pi0** [comment]
It would simply override stubs i guess (there are alternative ways to build dist: bundle|watch|stub)

**Comment by danawoodman** [comment]
dropping in to annoyingly +1 this 😇

**Comment by tibineagu** [comment]
@AbhiPrasad fingers crossed that you had a bit of time to work on this 🤞

**Comment by RSS1102** [comment]
🤔I also need this feature.May I ask when it can be pushed forward.

---
I hope it can support  **files in a key directory and listen to multiple directories**, because when I want to develop plugins, plugins and playgrounds are under the same `pwd()`.

**Comment by joemckenney** [comment]
@RSS1102 @jd-solanki take a peak at https://github.com/pkg-tools/pkg-tools/tree/main/packages/%40pkg-tools/build. 

I took a swing at implementing this in the PR linked above but I've also implemented it in a cleaner manner in the library I'm developing that wraps unbuild.

**Comment by Daydreamer-riri** [comment]
Hi , any progress?
